### ISSUE TITLE
Entities

### ISSUE THREAD

**Issue by Diekloper** [JuniorBuggyTimeTracker/MasterUnit#6]
@PoebelPogge 
As a result of our brainstorming, here an overview about the entities. If there is something missing, feel free to add it. 

**Driver:** 
Driver_ID 
RFID_Chip_ID 
Name 
Surname 
Date of birth 
Club 
Class 
Start number 
Guest starter true/false 

**Vehicel** 
Vehicel_ID 
Club (provides the vehicel for the event) 
Color (current there are three buggies, which are operatet by the clubs. They are currently seperated by colors) 
RFID_Chip_ID 

**Events** 
Venue 
Organising club 
Date 
Runs 
Length of track  

 

**Run** 
Sequential number 
Timestamp_start 
Driver_ID and Timestamp_Driver 
Driver_ID and penalty 
Driver ID and length of track 
Penallty  

**Measurement** 
???

**Comment by PoebelPogge** [comment]
Why is: 
Driver -> Date of birth 
necessary? Is the age of the driver relevant?

**Comment by PoebelPogge** [comment]
Id like to add:
**Club**
- Name
- City
- Address

**Comment by PoebelPogge** [comment]
Vehicel -> Color:
Which colors are available?

**Comment by PoebelPogge** [comment]
Shouldn't a run contain at lease two driver?
And does a run lasts two heats?
And what do you mean with:

- Driver_ID and Timestamp_Driver <- No Idea
- Driver_ID and penalty <- No Idea
- Driver ID and length of track <- No Idea
- Penallty <- should that be all penalties of all heats of one run summed up?

**Comment by Diekloper** [comment]
> Vehicel -> Color: Which colors are available?

black and yellow. We know the third color, when the buggy comes out of maintainance. If possible, please make the color editable

**Comment by Diekloper** [comment]
> Why is: Driver -> Date of birth necessary? Is the age of the driver relevant?

The Drivers are divided in two classes cause of their age. 
In one of the next issues the rating table/classification would be required.  



Here some advice, the classification after the 1st event 

[class1](https://motorsport.adac-weser-ems.de/fileadmin/ADAC_WEM/Bilder/04_Motorsport/Automobil/Junior_Buggy_Pokal/2024_04_20_Gesamtwertung_Klasse1_.pdf)

[class2](https://motorsport.adac-weser-ems.de/fileadmin/ADAC_WEM/Bilder/04_Motorsport/Automobil/Junior_Buggy_Pokal/2024_04_20_Gesamtwertung_Klasse2_.pdf)


A classification table after each event for each class is needed. This was the first race, so this table is also the classification for the championchip. With the 2nd race an extra tabel is needed.

**Comment by Diekloper** [comment]
> Id like to add: **Club**
> 
> * Name
> * City
> * Address

okay 4 the 1st moment

**Comment by Diekloper** [comment]
> Shouldn't a run contain at lease two driver? (maybe variable amount of driver?) And does a run lasts two heats? And what do you mean with:
> 
> * Driver_ID and Timestamp_Driver <- No Idea
> * Driver_ID and penalty <- No Idea
> * Driver ID and length of track <- No Idea
> * Penallty <- should that be all penalties of all heats of one run summed up?

i`ll create a drawing for this schema
